[workspace]
members = ["derive", "generator", "meta", "pest"]
resolver = "2"

package.authors = ["DragoÈ™ Tiselice <dragostiselice@gmail.com>"]
package.edition = "2021"
package.version = "0.1.0"

[workspace.dependencies]
pest = { path = "./pest" }
pest_meta = { path = "./meta" }
pest_generator = { path = "./generator" }
unicode-width = { version = "0.1.11" }
pest2 = { version = "2.7.6", package = "pest" }
